config/routes.rb
Rails.application.routes.draw do




  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  post :incoming, to: 'incoming#create'
  
  resources :bookmarks
  resources :topics
  resources :users
  resources :sessions
  root to: "welcome#index"

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base

  belongs_to :user 
  belongs_to :topic
  has_many :likes
  
end

app/models/likes.rb
class Likes < ActiveRecord::Base
  belongs_to :user
  belongs_to :bookmark
  
end

app/models/topic.rb
class Topic < ActiveRecord::Base

  has_many :bookmarks
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :topics
  has_many :bookmarks
  has_many :likes, through: :bookmarks 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def hello
  end
   
  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]    
  end
  helper_method :current_user
 end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @bookmarks = Bookmark.all

  end

  def new
    @bookmark = Bookmark.new
  end

  def edit
  end

  def show
  end

  def create
    @bookmark = Bookmark.new(params.require(:bookmark).permit(:title, :url))
    if @bookmark.save
      flash[:notice] = "Bookmark was saved"
      redirect_to bookmarks_path
    else
      render :new
  end
 end
end

app/controllers/incoming_controller.rb
class IncomingController < ApplicationController

  # http://stackoverflow.com/questions/1177863/how-do-i-ignore-the-authenticity-token-for-specific-actions-in-rails
  skip_before_action :verify_authenticity_token, only: [:create]

  def create
     # Take a look at these in your server logs
     # to get a sense of what you're dealing with.
     puts "INCOMING PARAMS HERE: #{params.to_yaml}"

    # You put the message-splitting and business
    # magic here.
    

     user = User.find_by_email(params[:sender])  
     topic = Topic.find_by_name(params[:subject])   
     url = URI.extract(params["stripped-html"]).first
     
     # Check if user is nil, if so, create and save a new user
     if user.nil? 
        user = User.new(
          email: params[:sender],
          password: 'helloworld')
        user.save
     end
    
     if topic.nil? 
        topic = Topic.new(
            name: params[:subject]
           )
        topic.save
     end
     # Check if the topic is nil, if so, create and save a new topic
    bookmark = user.bookmarks.new(url: url)
    bookmark.topic = topic
    bookmark.save
     # Now that we're sure we have a valid user and topic, build and save a new bookmark

    # Assuming all went well.
    head 200
  end
end


app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by_email(params[:email])
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to root_url, notice: "Logged in!"
      else        
        flash[:alert] = "Email or password invalid."
        render "new"
   end
  end
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out"  
 end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end

  def show
  end

  def new
    @topic = Topic.new
  end

  def edit
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new    
  end
  
  def create
    @user = User.new(params.require(:user).permit(:email, :password, :password_confirmation))
    if @user.save
       session[:user_id] = @user.id
       redirect_to root_url, notice: "Thanks for signing up!"
    else 
      render "new"
    end
  end   
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookmarks/edit.html.erb
<h1>Bookmarks#edit</h1>
<p>Find me in app/views/bookmarks/edit.html.erb</p>

app/views/bookmarks/index.html.erb
<h1>Bookmarks</h1>


<% @bookmarks.each do |bookmark| %>
   <div class="media">
     <div class="media-body">
       <h4 class="media-heading"><br>
         <%= link_to bookmark.url, bookmark.url, :target => "_blank" %>
       </h4>
     </div>
   </div>
<% end %>

app/views/bookmarks/new.html.erb
<h1>New Bookmarks</h1> 
 <div class="row">
  <div class="col-md-4">
    <p>Add New Bookmarks Here<p>
    <ul>
      <li>Simply give the bookmark a title</li>
      <li>...then paste in the url</li><br>
 <div class="col-md-8">  
  <%= form_for @bookmark do |f| %>
   <div class="form-group">
    <%= f.label :topic %> <br>
    <%= f.text_field :topic, class: 'form-control', placeholder: "enter topic here" %><br>
   </div>
   <div class="form-group">
    <%= f.label :url %><br>
    <%= f.text_field :url, rows: 2, class: 'form-control', placeholder: "enter url here" %><br><br>
   </div>
   <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
   </div>
  <% end %>
  </div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookmarkApp</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <div class="pull-right user-info">
      <% if current_user %>
      Logged in as <%= current_user.email %>
     <li><%= link_to "Log Out", session_path("current"), method: "delete" %></li>
      <% else %>      
        <li><%= link_to "Sign Up", signup_path %></li>
        <li><%= link_to "Log In", login_path %></li>   
      <% end %>
        </div>
      </ul>    
   
     <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:error] %>
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:error] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>
    
   <%= yield %>
  </div>
 </body>
</html>

app/views/topics/edit.html.erb
<h1>Topics#edit</h1>
<p>Find me in app/views/topics/edit.html.erb</p>

app/views/topics/index.html.erb
<h1>Topics</h1>


<% @topics.each do |topic| %>
  <p><%= link_to topic.name, topics_path %></p>
<% end %>

app/views/topics/new.html.erb
<h1>Topics#new</h1>
<p>Find me in app/views/topics/new.html.erb</p>

app/views/topics/show.html.erb
<h1>Topics#show</h1>

app/views/users/new.html.erb
<h2>Sign up</h2><br>
 <div class="row">
  <div class="col-md-8">
    <%= form_for @user do |f| %>      
     <% if @user.errors.any? %>
      <div class="error_messages">
       <h2>Form is invalid</h2>
        <ul>
        <% @user.errors.full_messages.each do |message| %> 
        <li><%= message %></li>
        <% end %> 
       <% end %> 
       </ul>
      </div>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control', placeholder: "Enter email" %>
      </div>
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control', placeholder: "Enter password" %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Enter password confirmation" %>
      </div>
      <div class="form-group">
        <%= f.submit "Sign up", class: 'btn btn-success' %>
      </div>      
    <% end %>
  </div>
</div>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>